# Generated by Django 5.0.4 on 2024-04-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_lists', '0002_alter_users_managers_users_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='telegram_id',
        ),
    ]
