# Generated by Django 5.0.6 on 2024-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='detail_name',
            field=models.CharField(max_length=100),
        ),
    ]
