# Generated by Django 5.1 on 2024-09-15 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('project', models.CharField(choices=[('Desiro', 'Ласточка'), ('Velaro', 'Сапсан'), ('Depot', 'Депо'), ('Sample print', 'Пробная печать')], max_length=100)),
                ('a2v_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True)),
                ('image_1', models.ImageField(upload_to='detail_images/')),
                ('image_2', models.ImageField(upload_to='detail_images/')),
                ('image_3', models.ImageField(upload_to='detail_images/')),
                ('image_4', models.ImageField(upload_to='detail_images/')),
                ('model_file', models.FileField(upload_to='detail_3d_models/')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ['added_date'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('location', models.CharField(choices=[('Podmoskovnaya', 'Подмосковная'), ('Andronovka', 'Андроновка'), ('Metallostroy', 'Металлострой'), ('Kaliningrad', 'Калининград'), ('Kryukovo', 'Крюково'), ('Ekaterinburg', 'Екатеринбург'), ('Samara', 'Самара'), ('Nizhny Novgorod', 'Нижний Новгород'), ('Chelyabinsk', 'Челябинск'), ('Adler', 'Адлер'), ('Perm', 'Пермь'), ('Ufa', 'Уфа')], default=0, max_length=100, verbose_name='Локация')),
                ('role', models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('operator', 'Оператор 3D принтера'), ('admin', 'Администратор')], default=0, max_length=120, verbose_name='Роль')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(choices=[('Podmoskovnaya', 'Подмосковная'), ('Andronovka', 'Андроновка'), ('Metallostroy', 'Металлострой'), ('Kaliningrad', 'Калининград'), ('Kryukovo', 'Крюково'), ('Ekaterinburg', 'Екатеринбург'), ('Samara', 'Самара'), ('Nizhny Novgorod', 'Нижний Новгород'), ('Chelyabinsk', 'Челябинск'), ('Adler', 'Адлер'), ('Perm', 'Пермь'), ('Ufa', 'Уфа')], default=0, max_length=100, verbose_name='Локация')),
                ('status', models.CharField(choices=[('processing', 'Заказ в обработке'), ('in_progress', 'Заказ выполняется'), ('ready', 'Заказ готов')], default='processing', max_length=20)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('detail_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['added_date'],
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users'),
        ),
    ]
