# Generated by Django 4.2.7 on 2023-11-14 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название детали')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('a2v', models.CharField(max_length=255, verbose_name='Проект')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(verbose_name='статус заказа')),
                ('data_order', models.DateTimeField(verbose_name='дата заказа')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('telegram_id', models.BigIntegerField(verbose_name='телеграмм_id')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('role', models.CharField(max_length=100, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='orders_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1!')], verbose_name='количество')),
                ('details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.details')),
                ('orders_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='image_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_img', models.ImageField(upload_to='media/')),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.details')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
